### PR TITLE
create HCTextFieldManager

### PR DESCRIPTION
**Pull request by Lebron1992**

### CODE REVIEW

**Comment by Lebron1992** [comment]
@laeroah I create unit test in the current branch, forgot to create a new branch to create it. About the UI test, I want to test the changes of textfield border color, but it seems there is no way to access the textfield border color when I write the UI test case.

**Review by laeroah — APPROVED** [review]
ok, let's merge :shipit:

**Comment by laeroah** [comment]
next step, we want to create view that we can add these textfields to. The view has to be constructed that if when the keyboard is raised, we want to animate the view so that the focused textfield can always be above keyboard doesn't matter where the textfield is.

**Comment by Lebron1992** [comment]
Sounds good!

**Pull request merged**
